{{- if and .Values.db.enabled (not .Values.db.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chap.fullname" . }}-db
  labels:
    {{- include "chap.componentLabels" (dict "ctx" . "component" "db") | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ required "Set db.password or db.existingSecret" .Values.db.password | quote }}
{{- else if and (not .Values.db.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chap.fullname" . }}-db
  labels:
    {{- include "chap.componentLabels" (dict "ctx" . "component" "db") | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.externalDatabase.username | quote }}
  password: {{ required "Set externalDatabase.password or externalDatabase.existingSecret" .Values.externalDatabase.password | quote }}
{{- end }}
