{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chap-db.fullname" . }}-postgres
  labels:
    {{- include "chap-db.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.cnpg.cluster.enabled }}
  username: {{ "postgres" | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- else if .Values.postgresql.external.enabled }}
  username: {{ .Values.postgresql.external.user | b64enc | quote }}
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
  {{- end }}
{{- end }}
