services:
  chap_r_model_test:
    init: true
    build:
      context: .
      dockerfile: Dockerfile.r-model.integrationtest
    container_name: chap_r_model_test
    depends_on:
      - chap
    command: python docker_db_flow_r_model.py chap
