services:
  chap_frontend_emulator:
    build:
      context: .
      dockerfile: Dockerfile.integrationtest
    container_name: chap_frontend_emulator
    depends_on:
      - chap
    networks:
      - chap-network
    command: 
      python docker_db_flow.py chap auto_regressive_monthly;
      python docker_db_flow.py chap naive_model;
