services:
  chap_frontend_emulator:
    build:
      context: .
      dockerfile: Dockerfile.integrationtest
    # for now some of the tests uses hardocded names so we need to set the container name
    container_name: chap_frontend_emulator
    depends_on:
      - chap
    command: 
      #python docker_db_flow.py chap rwanda_random_forest;
      python docker_db_flow.py chap naive_model;
