services:
  marketplace-chapkit-ewars-model:
    restart: unless-stopped
    init: true
    read_only: true
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    environment:
      SERVICEKIT_ORCHESTRATOR_URL: http://chap:8000/v2/services/$$register
      SERVICEKIT_REGISTRATION_KEY: ${SERVICEKIT_REGISTRATION_KEY:-}
      SERVICEKIT_HOST: marketplace-chapkit-ewars-model
    depends_on:
      chap:
        condition: service_healthy
    image: ghcr.io/chap-models/chapkit_ewars_model:sha-fa880a1
    x-chap-custom: false
    x-chap-version: 1.0.0
    x-chap-registry: https://raw.githubusercontent.com/dhis2-chap/model-marketplace/main
    platform: linux/amd64
    volumes:
    - marketplace-chapkit-ewars-model-data:/app/data
    - type: tmpfs
      target: /tmp
volumes:
  marketplace-chapkit-ewars-model-data: {}
