FROM python:3.13-slim

COPY tests/docker_db_flow.py docker_db_flow.py
COPY tests/docker_db_flow_configured_models.py docker_db_flow_configured_models.py

COPY example_data example_data
RUN pip install requests
