# Use the official Python base image
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Set the working directory in the container
WORKDIR /app

# Install the Python dependencies
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git

COPY ./chap_core ./chap_core
COPY ./pyproject.toml .
COPY ./README.md .
COPY ./external_models ./external_models
COPY ./example_data ./example_data
COPY ./tests ./tests
COPY .env* ./

RUN uv sync --dev
# CMD ["/app/.venv/bin/pytest", "/app/tests"]
