#THIS DOCKERFILE RUNS THE WEB API

# Use the official Python base image
FROM ghcr.io/astral-sh/uv:0.10-python3.13-trixie-slim

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Create non-root user early
RUN useradd -m -s /bin/bash chap && \
    mkdir -p /app && chown -R chap:chap /app

# Set the working directory in the container
WORKDIR /app

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --dev

# Install system dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends git make && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./chap_core ./chap_core
COPY ./config ./config
COPY ./pyproject.toml .
COPY ./uv.lock .
COPY ./README.md .
COPY ./alembic.ini .
COPY ./alembic ./alembic

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --dev

# Switch to non-root user
RUN mkdir /app/logs
RUN chown -R chap:chap /app
USER chap

# Ensure virtual environment is first in PATH
ENV PATH="/app/.venv/bin:$PATH"
