apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/dhis2-chap/chap-core
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/dhis2-chap/chap-worker
      docker:
        dockerfile: Dockerfile.worker
deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - name: chap
        chartPath: charts/chap
        namespace: chap
        createNamespace: true
        setValueTemplates:
          chap-api.image.pullPolicy: Always
          chap-worker.image.pullPolicy: Always
          chap-valkey.valkey.auth.aclUsers.default.password: "{{.REDIS_PASSWORD}}"
          chap-api.googleServiceAccount.email: "{{.GOOGLE_SERVICE_ACCOUNT_EMAIL}}"
          chap-api.googleServiceAccount.privateKey: "{{.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY}}"
          chap-api.ingress.enabled: "false"
