"""Generate docs/contributor/architecture_model.md from the Structurizr Mermaid export.

Reads ``architecture/exports/mermaid/structurizr-<ViewKey>.mmd`` (produced by
``structurizr export -format mermaid``) and rewrites each view into clean, native
Mermaid that renders inside MkDocs (Material, strict security): the HTML ``<div>``
labels Structurizr emits for PNG rendering are collapsed to plain text with
``<br/>`` breaks, and the hard-coded white canvas is dropped so the diagram adapts
to light/dark themes. The C4 node colours and shapes are kept.

Regenerate with ``make architecture-export-docs``. Do not edit the output by hand.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXPORT_DIR = ROOT / "architecture" / "exports" / "mermaid"
OUT = ROOT / "docs" / "contributor" / "architecture_model.md"

# Curated order + section titles for the known views.
VIEWS: list[tuple[str, str]] = [
    ("L1_Landscape", "L1 - System landscape"),
    ("L2_ChapCore", "L2 - Containers: CHAP Core"),
    ("L2_Chapkit", "L2 - Containers: chapkit model service"),
    ("L3_CoreAPI", "L3 - Components: CHAP Core REST API"),
    ("L3_CoreWorker", "L3 - Components: CHAP Core worker"),
    ("L3_ChapkitService", "L3 - Components: chapkit Service API"),
    ("Flow_IngestDataset", "Flow - Ingest a dataset"),
    ("Flow_Backtest", "Flow - Run a backtest"),
    ("Flow_Prediction", "Flow - Run a prediction"),
]


def clean_label(inner: str) -> str:
    """Collapse the HTML ``<div>`` label Structurizr emits into plain text + ``<br/>``."""
    parts = re.findall(r"<div[^>]*>(.*?)</div>", inner, re.DOTALL)
    cleaned = [re.sub(r"\s+", " ", p.replace("<br />", " ")).strip() for p in parts]
    return "<br/>".join(p for p in cleaned if p)


def clean_diagram(text: str) -> str:
    """Rewrite one exported ``.mmd`` into MkDocs-friendly native Mermaid."""
    text = re.sub(
        r'"((?:[^"]*<div[^"]*))"',
        lambda m: '"' + clean_label(m.group(1)) + '"',
        text,
    )
    lines: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        # Drop the hard-coded white canvas so the diagram follows the page theme.
        if stripped.startswith("linkStyle default fill:#ffffff"):
            continue
        if stripped.startswith("style diagram fill:#ffffff"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def main() -> None:
    if not EXPORT_DIR.exists():
        raise SystemExit(f"missing {EXPORT_DIR}; run `make architecture-export-docs`")

    found = {p.stem.replace("structurizr-", ""): p for p in EXPORT_DIR.glob("structurizr-*.mmd")}
    known = {key for key, _ in VIEWS}
    ordered = list(VIEWS) + [(k, k) for k in sorted(found) if k not in known]

    out: list[str] = [
        "# Architecture model (C4)",
        "",
        "<!-- GENERATED by `make architecture-export-docs` from architecture/workspace.dsl. Do not edit by hand. -->",
        "",
        "These diagrams are generated from the canonical Structurizr model in",
        "`architecture/workspace.dsl`, so they stay in sync with it. For the",
        "interactive, drill-down viewer and the other renderers, see",
        "`architecture/README.md`.",
        "",
        "See also the hand-drawn cross-repo overview in",
        "[Architecture diagrams](architecture_diagrams.md).",
        "",
    ]
    for key, title in ordered:
        path = found.get(key)
        if path is None:
            continue
        diagram = clean_diagram(path.read_text())
        out += [f"## {title}", "", "```mermaid", diagram, "```", ""]

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({sum(1 for k, _ in ordered if k in found)} views)")


if __name__ == "__main__":
    main()
