"""Generated list of backtest plot ids.

Auto-generated by scripts/regenerate_plot_help.py — do not edit by hand.
Run `make regen-plot-help` after adding or removing a @backtest_plot.
"""

BACKTEST_PLOT_IDS: tuple[str, ...] = (
    "evaluation_plot",
    "horizon_location_grid",
    "metrics_dashboard",
    "predicted_vs_actual",
    "ratio_of_samples_above_truth",
)
