apiVersion: v2
name: chap
description: CHAP (Climate Health Analysis Platform)
type: application
version: 1.1.1
appVersion: "v2.1.0"

dependencies:
  - name: valkey
    version: 0.9.2
    repository: "https://valkey.io/valkey-helm"
    condition: valkey.enabled

annotations:
  category: Application
