"""Regenerate chap_core/cli_endpoints/generated_plot_ids.py.

Scans chap_core/assessment/backtest_plots/*.py for `@backtest_plot(id="...")`
decorator calls using AST parsing only — no chap_core imports — so the
script is fast and has no heavy dependencies.

Output is sorted and formatted deterministically: running the script
twice with no source changes produces byte-identical output and the
second run prints "No changes".
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLOT_SOURCE_DIR = REPO_ROOT / "chap_core" / "assessment" / "backtest_plots"
TARGET_FILE = REPO_ROOT / "chap_core" / "cli_endpoints" / "generated_plot_ids.py"


def _extract_plot_ids_from_file(path: Path) -> list[str]:
    """Return all `plot_id="..."` values passed to @backtest_plot(...) in `path`."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    ids: list[str] = []
    for node in ast.walk(tree):
        for decorator in getattr(node, "decorator_list", []):
            if not isinstance(decorator, ast.Call):
                continue
            func = decorator.func
            name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", None)
            if name != "backtest_plot":
                continue
            for kw in decorator.keywords:
                if kw.arg == "plot_id" and isinstance(kw.value, ast.Constant) and isinstance(kw.value.value, str):
                    ids.append(kw.value.value)
    return ids


def scan_plot_ids() -> tuple[str, ...]:
    ids: set[str] = set()
    for path in sorted(PLOT_SOURCE_DIR.rglob("*.py")):
        ids.update(_extract_plot_ids_from_file(path))
    return tuple(sorted(ids))


def render_module(ids: tuple[str, ...]) -> str:
    body = "\n".join(f'    "{plot_id}",' for plot_id in ids)
    return (
        '"""Generated list of backtest plot ids.\n'
        "\n"
        "Auto-generated by scripts/regenerate_plot_help.py — do not edit by hand.\n"
        "Run `make regen-plot-help` after adding or removing a @backtest_plot.\n"
        '"""\n'
        "\n"
        "BACKTEST_PLOT_IDS: tuple[str, ...] = (\n"
        f"{body}\n"
        ")\n"
    )


def main() -> int:
    ids = scan_plot_ids()
    if not ids:
        print(f"error: no @backtest_plot decorators found under {PLOT_SOURCE_DIR}", file=sys.stderr)
        return 1

    new_content = render_module(ids)
    existing = TARGET_FILE.read_text(encoding="utf-8") if TARGET_FILE.exists() else ""

    if existing == new_content:
        print(f"No changes: {TARGET_FILE.relative_to(REPO_ROOT)} ({len(ids)} ids)")
        return 0

    TARGET_FILE.write_text(new_content, encoding="utf-8")
    print(f"Updated: {TARGET_FILE.relative_to(REPO_ROOT)} ({len(ids)} ids)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
