{{- if and .Values.api.enabled .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chap.componentServiceAccountName" (dict "ctx" . "component" "api") }}
  labels:
    {{- include "chap.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.api.serviceAccount.automount }}
{{- end }}
